---
- hosts: all
  gather_facts: false
  tags: [verify]
  vars:
    bgp_underlay: "show ip bgp summary | i {{ item['ip'] }}.*Estab"
    bgp_overlay: "show bgp evpn summary| i {{ item['ip'] }}.*Estab"
  tasks:
    - name: "underlay bgp test"
      raw: "{{ bgp_underlay }}"
      register: underlay_status
      with_items: "{{ peers_underlay }}"
      failed_when: underlay_status.stdout == ""

    - name: "overlay bgp test"
      raw: "{{ bgp_overlay }}"
      register: overlay_status
      with_items: "{{ peers_overlay }}"
      failed_when: overlay_status.stdout == ""
