---  ### alterntive play to do the same thing in bgp_test.yml file
- hosts: all
  gather_facts: false
  tags: [verify]
  vars:
    bgp_underlay: "show ip bgp summary"
    bgp_overlay: "show bgp evpn summary"
    pattern: '{{ item.ip }}(.*)Estab'

  tasks:
    - name: "underlay bgp test"
      raw: "{{ bgp_underlay }}"
      with_items: "{{ peers_underlay }}"
      register: underlay_status
      failed_when: not underlay_status.stdout is regex(pattern)

    - name: "overlay bgp test"
      raw: "{{ bgp_overlay }}"
      with_items: "{{ peers_overlay }}"
      register: overlay_status
      failed_when: not overlay_status.stdout is regex(pattern)
