---
- hosts: leaf
  gather_facts: false
  tags: [verify]
  vars_files:
    - ../../../Step2-config/roles/services_config/vars/main.yml

  tasks:
    - name: collect the vlan database
      raw: "show vlan brief"
      register: vlan_db

    - name: compare vlan/port mappings against the vlan_db
      set_fact:
        fact1: "{{ item.1.vlan_id }}"
        fact2: "{{ item.0.name }}"
        fact3: "{{ item.1.sap[inventory_hostname] | join('.*')}}"
      when: "inventory_hostname in item.1.sap"
      failed_when: not vlan_db.stdout_lines is regex(fact1 + '.*' + fact2 + '.*' + fact3)
      with_subelements:
        - "{{ customers }}"
        - services
