---
- hosts: leaf
  gather_facts: false
  vars:
    cli_commands: "show ip arp vrf {{ customer }} {{ ip_address }}"
    output: "get_outputs"
    cust: "{{ customer }}"
    ip: "{{ ip_address }}"

  pre_tasks:
    - file:
        path: "{{ output }}"
        state: absent
      delegate_to: localhost
      run_once: true

    - file:
        path: "{{ output }}"
        state: directory
      delegate_to: localhost
      run_once: true

  tasks:

    - raw: "{{ cli_commands }}"
      register: cli_output

    - name: save ARP entries
      copy:
        content: |
            =====================================
            {{ ip }} seen on {{ inventory_hostname}}
            =====================================
            {% for line in cli_output.stdout_lines[1:] %}
            {{ line }}
            {% endfor %}
            
        dest: "{{ output }}/{{ inventory_hostname}}_{{ cust }}_{{ ip }}_arp.txt"
      delegate_to: localhost
      when: "ip in cli_output.stdout"

  post_tasks:
    - assemble:
        src: "{{ output }}"
        dest: "{{ output }}/arp_{{ ip }}_in_vrf_{{ cust }}.txt"
      delegate_to: localhost
      run_once: true

