- hosts: leaf
  serial: 1
  gather_facts: no 
  vars:
    cli_commands:   "show ip arp vrf {{ customer }}"
    output: "get_outputs/{{ customer }}_arps.txt"
    cust: "{{ customer }}"
    ip: "{{ ip_address }}"
                   
  pre_tasks:
    - file:
        path: "{{ output }}"
        state: absent
      delegate_to: localhost
      run_once: True
      when: inventory_hostname == ansible_play_hosts_all[0] 
    - file:
        path: "{{ output }}"
        state: touch
      delegate_to: localhost
      run_once: True
      when: inventory_hostname == ansible_play_hosts_all[0] 

  tasks:

    - raw: "{{ cli_commands }}"
      register: cli_output
      
    - name: save ARP tables
      lineinfile:
        line: |
            =====================================
            ARP Table of {{ cust }} on {{ inventory_hostname }}
            =====================================
            {% for line in cli_output.stdout_lines[1:] %}
            {{ inventory_hostname}} {{ cust }} {{ line }}
            {% endfor %}
        dest: "{{ output }}"
        create: no
      delegate_to: localhost
      
  post_tasks:      
    - raw: "grep {{ ip }} {{output}} | cat"
      register: grepOutput
      delegate_to: localhost
      run_once: True
      when: inventory_hostname == ansible_play_hosts_all[-1]
    - debug: var=grepOutput.stdout_lines
      delegate_to: localhost
      run_once: True
      when: inventory_hostname == ansible_play_hosts_all[-1] 
