---
- hosts: leaf
  gather_facts: false
  vars:
    cli_commands: "show mac address-table address {{ mac_address }}"
    output: "get_outputs"
    mac: "{{ mac_address }}"

  pre_tasks:
    - file:
        path: "{{ output }}"
        state: absent
      delegate_to: localhost
      run_once: true

    - file:
        path: "{{ output }}"
        state: directory
      delegate_to: localhost
      run_once: true

  tasks:

    - raw: "{{ cli_commands }}"
      register: cli_output

    - name: save MAC entries
      copy:
        content: |
            =====================================
            {{ mac }} seen on {{ inventory_hostname}}
            =====================================
            {% for line in cli_output.stdout_lines[1:] %}
            {{ line }}
            {% endfor %}
        dest: "{{ output }}/{{ inventory_hostname}}_{{ mac }}_mac.txt"
      delegate_to: localhost
      when: "mac in cli_output.stdout"

  post_tasks:
    - assemble:
        src: "{{ output }}"
        dest: "{{ output }}/mac_{{ mac }}_in_fabric.txt"
      delegate_to: localhost
      run_once: true
