---
- hosts: leaf
  gather_facts: false
  vars:
    cli_commands: "show interfaces desc | inc {{ customer }} "
    output: "get_outputs"
    cust: "{{ customer }}"

  pre_tasks:
    - file:
        path: "{{ output }}"
        state: absent
      delegate_to: localhost
      run_once: true
    - file:
        path: "{{ output }}"
        state: directory
      delegate_to: localhost
      run_once: true

  tasks:

    - raw: "{{ cli_commands }}"
      register: cli_output

    - name: save if descriptions matching the customer for each leaf
      copy:
        content: |
            =====================================
            {{ cust }} is connected to {{ inventory_hostname}} on following ports:
            =====================================
            {% for line in cli_output.stdout_lines[0:] %}
            {{ line }}
            {% endfor %}
        dest: "{{ output }}/{{ inventory_hostname}}_{{ cust }}_port.txt"
      delegate_to: localhost
      when: "cust in cli_output.stdout"

  post_tasks:
    - assemble:
        src: "{{ output }}"
        dest: "{{ output }}/{{ cust }}_ports_in_fabric.txt"
      delegate_to: localhost
      run_once: true
