---
- hosts: leaf
  serial: 1
  gather_facts: false
  vars:
    cli_commands: "show interfaces desc"
    output: "get_outputs/cust-ports.txt"
    cust: "{{ customer }}"

  pre_tasks:
    - file:
        path: "{{ output }}"
        state: absent
      delegate_to: localhost
      run_once: true
      when: inventory_hostname == ansible_play_hosts_all[0]
    - file:
        path: "{{ output }}"
        state: touch
      delegate_to: localhost
      run_once: true
      when: inventory_hostname == ansible_play_hosts_all[0]

  tasks:

    - raw: "{{ cli_commands }}"
      register: cli_output

    - name: save if descriptions
      lineinfile:
        line: |
            =====================================
            Interface Descriptions of {{ inventory_hostname }}
            =====================================
            {% for line in cli_output.stdout_lines[1:] %}
            {{ inventory_hostname}} {{ line }}
            {% endfor %}
        dest: "{{ output }}"
        create: false
      delegate_to: localhost

  post_tasks:
    - raw: "grep {{ cust }} {{output}} | cat"
      register: grepOutput
      delegate_to: localhost
      run_once: true
      when: inventory_hostname == ansible_play_hosts_all[-1]
    - debug: var=grepOutput.stdout_lines
      delegate_to: localhost
      run_once: true
      when: inventory_hostname == ansible_play_hosts_all[-1]
