---
asn: "65001"
router_id: "192.168.0.1"
remote_asn: "65000"

interfaces:
    - name: "lo0"
      ip_address: "192.168.0.1/32"
      desc: "for routing protocols"
    - name: "lo1"
      ip_address: "192.168.1.1/32"
      desc: "for VxLAN Tunnel"
    - name: "Eth1"
      ip_address: "172.16.1.2/30"
      desc: "to_spine-1"
    - name: "Eth2"
      ip_address: "172.16.1.10/30"
      desc: "to_spine-1"

peers_underlay:
    - ip: "172.16.1.1"
    - ip: "172.16.1.9"

peers_overlay:
    - ip: "192.168.2.1"
    - ip: "192.168.2.2"
