---
- hosts: all
  gather_facts: false
  tags: [diff]
  vars:
    cli_commands: "config session {{ timestamp.stdout }}\ncopy flash:{{ inventory_hostname }}.cfg session-config\nshow session-config diffs"

  tasks:

    - name: collect date and time for folder/file naming
      shell: date +"%Y-%m-%d-%H-%M"
      register: timestamp
      delegate_to: localhost
      run_once: true

    - raw: "{{ cli_commands }}"
      register: diff

    - debug: var=diff.stdout_lines
